import Foundation
import SwiftUI
import Combine
import CryptoKit

// MARK: - Entry model
//
// One row in the History page. Two flavors:
//
//   • .manual — generated by the Repair Guide flow. References a cached
//     RepairManual via its query hash (same hash RepairGuideCache uses), so
//     opening the entry replays the full step-by-step doc with images.
//   • .qa     — a single Q&A turn from the voice session. Holds the spoken
//     question and Otto's answer text inline (no image set).

struct HistoryEntry: Codable, Identifiable, Hashable {
    enum Kind: String, Codable, Hashable { case manual, qa }

    let id: UUID
    var query: String
    var title: String
    var createdAt: Date
    var kind: Kind

    // Manual-flavor fields
    var manualKey: String?       // SHA-256 of normalized query (matches RepairGuideCache)
    var stepCount: Int?
    var thumbnailPath: String?   // first step's PNG path, if available

    // Q&A-flavor fields
    var answer: String?

    static func keyFor(query: String) -> String {
        let normalized = query.lowercased().trimmingCharacters(in: .whitespacesAndNewlines)
        let digest = SHA256.hash(data: Data(normalized.utf8))
        return digest.map { String(format: "%02x", $0) }.joined()
    }
}

// MARK: - Store
//
// Persists entries to a single JSON file in Caches. Newest first.
// Manual saves dedupe by manualKey — re-asking the same question updates the
// existing row instead of stacking duplicates. Q&A saves always append.

@MainActor
final class HistoryStore: ObservableObject {
    /// Process-wide shared instance. Both OttoStore and RepairGuideStore write
    /// through this so the History page stays consistent across screens.
    static let shared = HistoryStore()

    @Published private(set) var entries: [HistoryEntry] = []

    private var indexURL: URL {
        let dir = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("OttoHistory", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("history.json")
    }

    init() { load() }

    func load() {
        guard let data = try? Data(contentsOf: indexURL),
              let decoded = try? JSONDecoder().decode([HistoryEntry].self, from: data) else {
            entries = []
            return
        }
        entries = decoded.sorted { $0.createdAt > $1.createdAt }
    }

    private func persist() {
        if let data = try? JSONEncoder().encode(entries) {
            try? data.write(to: indexURL)
        }
    }

    // MARK: Saves

    /// Called from the Repair Guide flow once a manual (and its images) is ready.
    func saveManual(_ manual: RepairManual) {
        let key = HistoryEntry.keyFor(query: manual.query)
        let thumb = manual.steps.first?.imagePNGPath
        let entry = HistoryEntry(
            id: UUID(),
            query: manual.query,
            title: manual.title,
            createdAt: Date(),
            kind: .manual,
            manualKey: key,
            stepCount: manual.steps.count,
            thumbnailPath: thumb,
            answer: nil
        )
        // Replace any prior entry for the same manual so the row keeps moving
        // to the top with a fresh timestamp instead of accumulating duplicates.
        entries.removeAll { $0.kind == .manual && $0.manualKey == key }
        entries.insert(entry, at: 0)
        persist()
    }

    /// Called from the voice session after Otto answers a question.
    func saveQA(question: String, answer: String) {
        let trimmedQ = question.trimmingCharacters(in: .whitespacesAndNewlines)
        let trimmedA = answer.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedQ.isEmpty, !trimmedA.isEmpty else { return }
        let entry = HistoryEntry(
            id: UUID(),
            query: trimmedQ,
            title: trimmedQ,
            createdAt: Date(),
            kind: .qa,
            manualKey: nil,
            stepCount: nil,
            thumbnailPath: nil,
            answer: trimmedA
        )
        entries.insert(entry, at: 0)
        persist()
    }

    func delete(_ entry: HistoryEntry) {
        entries.removeAll { $0.id == entry.id }
        persist()
    }

    // MARK: Lookup helpers

    /// Resolve a manual entry back to the full cached RepairManual (with steps + images).
    func loadManual(for entry: HistoryEntry) -> RepairManual? {
        guard entry.kind == .manual else { return nil }
        return RepairGuideCache().load(for: entry.query)
    }

    /// Human-friendly relative timestamp for a row (e.g. "Today · 3:42pm", "Apr 15 · 9:11am").
    func relativeMeta(for entry: HistoryEntry) -> String {
        let cal = Calendar.current
        let timeFmt = DateFormatter()
        timeFmt.dateFormat = "h:mma"
        timeFmt.amSymbol = "am"
        timeFmt.pmSymbol = "pm"
        let timeStr = timeFmt.string(from: entry.createdAt).lowercased()

        if cal.isDateInToday(entry.createdAt) {
            return "Today · \(timeStr)"
        }
        if cal.isDateInYesterday(entry.createdAt) {
            return "Yesterday · \(timeStr)"
        }
        let dateFmt = DateFormatter()
        dateFmt.dateFormat = "MMM d"
        return "\(dateFmt.string(from: entry.createdAt)) · \(timeStr)"
    }

    /// Right-side caption — "5 steps" for manuals, "Q&A" for voice answers.
    func tail(for entry: HistoryEntry) -> String {
        switch entry.kind {
        case .manual: return "\(entry.stepCount ?? 0) steps"
        case .qa:     return "Q&A"
        }
    }
}
